# .github/workflows/lighthouse.yml

name: Lighthouse

on: push

jobs:
  performance-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Lighthouse
      uses: treosh/lighthouse-ci-action@v2
      with:
        urls: |
          https://kylehossli.com/
        # Lighthouse categories to focus on
        configPath: ./lighthouse/config.json # Path to the custom Lighthouse configuration
