name: Linting Error Report
run-name: I, ${{ github.actor}}, submit this log, my newest log since  my last log, so it may join the many others that preceeded it to mapmeasurement of his coding competence
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.6"

      - name: Install Dependencies
        run: npm install

      - name: Run Stylelint
        run: npx stylelint "**/*.css" --config .stylelintrc.json || echo "Stylelint found issues."

      - name: Run HTMLHint
        run: npx htmlhint "**/*.html" --config .htmlhintrc || echo "HTMLHint found issues."
