name: SuperLint

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'DEBUG'
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Super-Linter
        uses: docker://github/super-linter:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_TERRAFORM_TERRASCAN: false

      - name: Upload Linter Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linter-reports
          path: /github/workspace/super-linter.report

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          subject: Github Actions job result
          to: hosslikw@gmail.com
          from: hosslikw@gmail.com # <user@example.com>
          attachments: /github/workspace/super-linter.report