# This GitHub Actions workflow updates the Browserslist database in the repository.
# It is triggered manually via the workflow_dispatch event.

name: Update Browserslist database

on: # yamllint disable-line rule:truthy
  workflow_dispatch: # Trigger the workflow manually

permissions:
  contents: write # Grants write access to repository contents
  pull-requests: write # Grants write access to pull requests

jobs:
  update-browserslist-database:
    runs-on: ubuntu-latest # Specifies the runner environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out the repository
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      - name: Configure git
        run: |
          git config --global user.email "action@github.com" # Sets the global git user email
          git config --global user.name "GitHub Action" # Sets the global git user name

      - name: browserslist-update-action
        uses: c2corg/browserslist-update-action@v2.4.0 # Uses the Browserslist update action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
          branch: browserslist-update # The branch to create for the update
          base_branch: Main # The base branch to compare against
          commit_message: "build: update Browserslist db" # Commit message for the update
          title: "build: update Browserslist db" # Title of the pull request
          body: Auto-generated by [browserslist-update-action](https://github.com/c2corg/browserslist-update-action/) # Body of the pull request
          labels: "chores, github action" # Labels to add to the pull request
          reviewers: "user1,user2,user3" # Reviewers to request for the pull request
          teams: "team1" # Teams to request for the pull request
